version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - copyloopvar
    - whitespace
    - bodyclose
    - noctx
    - exhaustive
    - nilerr
    - errorlint
    - tparallel

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - paramTypeCombine
      - assignOp

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  exhaustive:
    default-signifies-exhaustive: true

  errorlint:
    errorf-multi: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam
        - paralleltest

    - path: testing/
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
